version: "1"
services:
  lmql:
    image: 4mbroise/adbl2:lmql-cpu
    network_mode: "host" 
    ports:
      - 4000:4000
  
  api:
    image: 4mbroise/adbl2:api
    network_mode: "host" 
    ports:
      - 10250:10250 
  
  frontend:
    image: 4mbroise/adbl2:ui-local
    network_mode: "host" 
    ports:
      - 27019:27019
