name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Delete huge unnecessary tools folder
  #     run: rm -rf /opt/hostedtoolcache
  #   - uses: actions/checkout@v4
  #   - name: Build the Docker image
  #     run: docker build . --file ./backend/lmql-server-dockerfile --tag ${{ secrets.USERNAME }}/adbl2:latest
  #   - name: login to docker Hub
  #     run: docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}
  #   - name: push
  #     run: docker push ${{ secrets.USERNAME }}/adbl2:latest

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file ./adbl2/dockerfile --tag ${{ secrets.USERNAME }}/adbl2:ui
    - name: login to docker Hub
      run: docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}
    - name: push
      run: docker push ${{ secrets.USERNAME }}/adbl2:ui
